### ISSUE TITLE
Ground constraint

### ISSUE THREAD

**Issue by lhthq** [PJLab-ADG/Livox-Mapping#11]
嘿！谢谢您出色的工作！想询问个问题，如果在上下坡这种斜面 地面约束会增大误差吗？hdl_graph_slam的地面约束是在平面上建立的。谢谢！

**Comment by SiyuanHuang95** [comment]
Hi

我们暂时没有在上下坡进行过测试，本项目是针对园区开发的。

从地面约束的原理来看，我感觉似乎不太适用，你可以做一下实验验证一下。欢迎后续进行同步！

**Comment by SiyuanHuang95** [comment]
Since no update, I will close this issue. You are welcome to re-open it when there is any update.

**Comment by InterKnight** [comment]
> 嘿！谢谢您出色的工作！想询问个问题，如果在上下坡这种斜面 地面约束会增大误差吗？hdl_graph_slam的地面约束是在平面上建立的。谢谢！

您好，请问有试验结果可以分享一下吗？

**Comment by SiyuanHuang95** [comment]
> > 嘿！谢谢您出色的工作！想询问个问题，如果在上下坡这种斜面 地面约束会增大误差吗？hdl_graph_slam的地面约束是在平面上建立的。谢谢！
> 
> 您好，请问有试验结果可以分享一下吗？

如果进一步提问，请reopen该issue或者新开issue @InterKnight 
如果希望向lhthq提问，可以直接@这位同学

**Comment by leslieburke** [comment]
我测试了一下上坡的场景，轨迹直接飞了，请问有什么改进的思路吗？@SiyuanHuang95 @InterKnight

**Comment by SiyuanHuang95** [comment]
现在的地面估计是假定水平面，可以把这个假设稍微放松下 @leslieburke
