### ISSUE TITLE
IMU_LiDAR params

### ISSUE THREAD

**Issue by ManChrys** [PJLab-ADG/Livox-Mapping#17]
Hello again my friend ,
I understand what do you mean in #16  but as I'm new, how can I find these parameters ? I tried LiDAR-imu-init repository but the results are not good. I got something like that

> Initialization result:
Rotation LiDAR to IMU (degree)     =  80.540787 -36.750309  78.788532
Translation LiDAR to IMU (meter)   = -0.141204  0.223906  0.390454
Time Lag IMU to LiDAR (second)     = -18.262039
Bias of Gyroscope  (rad/s)         =  0.051176 -0.071062 -0.004010
Bias of Accelerometer (meters/s^2) = -0.005226  0.015899 -0.003477
Gravity in World Frame(meters/s^2) = -7.115069 -6.738784 -0.447985

> Homogeneous Transformation Matrix from LiDAR to IMU: 
 0.155873 -0.276107  0.948403 -0.141204
 0.785972 -0.546882 -0.288390  0.223906
 0.598291  0.790370  0.131768  0.390454
 0.000000  0.000000  0.000000  1.000000

> Refinement result:
Rotation LiDAR to IMU (degree)     =  82.048534 -36.625378  77.469056
Translation LiDAR to IMU (meter)   = -0.274615  0.277822  0.348879
Time Lag IMU to LiDAR (second)     = -18.262039
Bias of Gyroscope  (rad/s)         =  0.257372 -0.246300 -0.139832
Bias of Accelerometer (meters/s^2) = -0.005012  0.015841 -0.003373
Gravity in World Frame(meters/s^2) = -7.115129 -6.738791 -0.448222

> Homogeneous Transformation Matrix from LiDAR to IMU: 
 0.174212 -0.263379  0.948832 -0.274615
 0.783446 -0.546662 -0.295589  0.277822
 0.596543  0.794853  0.111108  0.348879
 0.000000  0.000000  0.000000  1.000000

How can I calib my imu(mti g 710 )with LiDAR (livox mid 40)?? There is any repo ? 

**EDIT**

**The values are too big because i did fast calib with lil-init just to show you the type of extracting data.**

Thanks in advance .

**Comment by SiyuanHuang95** [comment]
The calibration parameters in our repo are from the Livox-supplier, where IMU is built-in style.

**Comment by SiyuanHuang95** [comment]
maybe you can check the repo also from PJLAB-ADG: https://github.com/PJLab-ADG/SensorsCalibration
