### ISSUE TITLE
GPS topic

### ISSUE THREAD

**Issue by ManChrys** [PJLab-ADG/Livox-Mapping#18]
Hello,

Livox_Mapping topics are 

    Livox LiDAR: /livox/lidar
    IMU: /livox/imu
    GPS: /localization/navstate_info

my topics are 

    Livox LiDAR: /livox/lidar
    IMU: /imu/data (Type: sensor_msgs/Imu)
    GPS: /gnss (Type: sensor_msg/NavSatFix)

i rename imu topic from /imu/data to /livox/imu using `rosrun rosbag topic_renamer.py`

but i cant do the same for GPS cause it has different msg type. Is there any way to run the package with my topics ? Thank you.

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest in our project.

Your write one simple python script with rosbag python package, where you load the information and rename it. 

And the detailed definition of the topic could be found: https://github.com/PJLab-ADG/Livox-Mapping/blob/main/ad_localization_msgs/msg/NavStateInfo.msg

**Comment by SiyuanHuang95** [comment]
You can check the processed lidar point cloud (line/point features), which should not be empty for the cost function calculation.

**Comment by SiyuanHuang95** [comment]
So place check your point cloud :)

To see whether your environment is feature-less

**Comment by SiyuanHuang95** [comment]
Any further follow-up update is wellcome!

**Comment by SiyuanHuang95** [comment]
Hi

The most naive and straightforward solution is:

extracting every element from NavSatFix_type in http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/NavSatFix.html

and fill the element in navestate_info ->  https://github.com/PJLab-ADG/Livox-Mapping/blob/main/ad_localization_msgs/msg/NavStateInfo.msg

**Comment by SiyuanHuang95** [comment]
The error suggests that the required topic is different from the fed-in one. You should have check.

Or, you can directly modify the msg definition.

**Comment by SiyuanHuang95** [comment]
Sry for late response, i am busy currently with my paper issue.

You can define the msg-type as you wish.

One example can be found here: http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv
