### ISSUE TITLE
support other type lidar

### ISSUE THREAD

**Issue by qweesiic** [PJLab-ADG/Livox-Mapping#2]
great job!!!
does it support other type lidar, such as velodyne\robosense and so on ?

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest!

To support other types of lidar, some modification works are needed:
1. You need one external IMU to publish the information. Also, extrinsic information is also needed.
2. If the point cloud pattern is different from Livox, the feature extraction block needs to de updated accordingly.
3.  The backend for LIOs with different types of lidar is similar.



Bests,

**Comment by qweesiic** [comment]
> Hi, thanks for your interest!
> 
> To support other types of lidar, some modification works are needed:
> 
> 1. You need one external IMU to publish the information. Also, extrinsic information is also needed.
> 2. If the point cloud pattern is different from Livox, the feature extraction block needs to de updated accordingly.
> 3. The backend for LIOs with different types of lidar is similar.
> 
> Bests,

thank you for your reply!
