### ISSUE TITLE
ubuntu 20.04 bug fixed

### ISSUE THREAD

**Issue by valenbase** [PJLab-ADG/Livox-Mapping#20]
Thanks for your work.

I used the code under ubuntu 20.04, which meets two bugs,
1) scans crash
`int FreeSeg(float *fPoints,int *pLabel,int pointNum)`
 adds return value;
`int PCSeg::DoSeg(int *pLabel1, float* fPoints1, int pointNum)`
 adds return value;
2) pose estimation crash
`double ComputeError(const Eigen::Matrix4d& pose)`
 adds return error;

**Comment by greenhand1216** [comment]
hi bro, could u please be more specific, thx a lot!!!
