### ISSUE TITLE
How to implement the ground constraint by using GTSAM

### ISSUE THREAD

**Issue by sonphambk** [PJLab-ADG/Livox-Mapping#22]
Hi. Thank you for your great work.
I saw that in the source you also use the ground constraint to align Point Cloud with gravity.
I want to implement it in LIO-SAM by using GTSAM.
Do you have idea or convert it to the GTSAM instead of Ceres?
Thanks

**Comment by SiyuanHuang95** [comment]
Hi since we did not have experience with GTSAM, no further help could be offered. And currently no such plan.

You may directly refer to the official tutorial.
