### ISSUE TITLE
Normal information of the point cloud

### ISSUE THREAD

**Issue by Milalaa** [PJLab-ADG/Livox-Mapping#25]
Hi！
How do you obtain the normal vector information of the point cloud? 
I know that the point cloud normal vector information is assigned in LidarFeatureExtractor.cpp, but I don't understand the rationale behind this.
Can such a normal vector assignment method be put into other LiDAR point clouds?
Looking forward to your reply！

**Comment by SiyuanHuang95** [comment]
1. Just follow the normal procedure of LOAM-series. You can refer to those papers to get detailed info.
2. The lidar processing is always in a statistic way, similar to norm calculation.

**Comment by Milalaa** [comment]
Thanks for your reply！
