### ISSUE TITLE
About Fitting the local ground plane

### ISSUE THREAD

**Issue by Milalaa** [PJLab-ADG/Livox-Mapping#27]
Thank you for your excellent work!
I have two questions for you.
1. Is the lidarframelist holding the poses in the lidar coordinate system?
2. What is the logic in Cost_NavState_PR_Ground? Is the P and Q (translation and rotation) in lidarframelist converted to the world coordinate system? And how is the local ground plane calculated?

I am new in this field, and the transformation makes me confused. I'm sorry for all the questions and look forward to your reply!

**Comment by SiyuanHuang95** [comment]
1. poses aligned with the lidar coordinate system. If so, should it be an identity matrix?
2. For the local ground, I suggest you look in LOAM or Lego-LOAM. Most LOAM follows that typical logic.

Bests
