### ISSUE TITLE
PoseEstimation node crash

### ISSUE THREAD

**Issue by lacie-life** [PJLab-ADG/Livox-Mapping#30]
Thanks for your great work. When I try your code with the bag file from my Lidar (Mid 40). I met this problem:
`ground_cloud size: 6992
[get_plane_coeffs]: 1
[get_plane_coeffs]: 2
pointNum = 10000 gcnt = 456 gnum = 456
pointNum = 10000 gcnt = 461 gnum = 461
[PoseEstimation-3] process has died [pid 15982, exit code -11, cmd /home/lacie/workspace/fusion_ws/devel/lib/livox_odometry/PoseEstimation __name:=PoseEstimation __log:=/home/lacie/.ros/log/38ce41e8-0ebc-11ee-914f-b79cd7953d6e/PoseEstimation-3.log].
log file: /home/lacie/.ros/log/38ce41e8-0ebc-11ee-914f-b79cd7953d6e/PoseEstimation-3*.log
pointNum = 10000 gcnt = 414 gnum = 414
pointNum = 10000 gcnt = 451 gnum = 451
pointNum = 10000 gcnt = 437 gnum = 437
pointNum = 10000 gcnt = 426 gnum = 426
pointNum = 10000 gcnt = 467 gnum = 467
pointNum = 10000 gcnt = 412 gnum = 412
pointNum = 10000 gcnt = 457 gnum = 457
pointNum = 10000 gcnt = 426 gnum = 426
pointNum = 10000 gcnt = 413 gnum = 413`

The terminal of livox_mapping is fine but nothing in rviz.

Are you have any suggestions for me?

Moreover, I have confused about which version of ceres, because I built successful your source code with ceres 1.14 but cannot build with ceres 2.0.0 like [this](https://github.com/PJLab-ADG/Livox-Mapping/issues/3#issuecomment-1047714050)

Thanks!

**Comment by SiyuanHuang95** [comment]
thanks for your interest!

we did not test it with other lidar types.  can you check your log file for more information?

The environment is slightly complex, so a docker would be suggested.
