### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by FengyuGuo** [PJLab-ADG/Livox-Mapping#32]
https://github.com/PJLab-ADG/Livox-Mapping/blob/38bc18f15ad84a734618002c64f5ae5fbb19513e/LIO-Livox/src/lio/ScanRegistration.cpp#L34

It seems that this line will introduce problem if the lidar  is time synced with computer with ptp.

when pose estimation try to fetch imu message from queue the time stamp will be not matched.

[ INFO] [1695366188.427859228]: imu back time: 1678001245.552871, imu front time: 1678001244.927890, request start time: 136.299666, request end time: 136.399515

lidar is synced with computer follow the below link

https://github.com/Livox-SDK/Livox-SDK/wiki/livox-device-time-synchronization-manual

**Comment by SiyuanHuang95** [comment]
I did not notice this problem before...

This script is mainly brought from LIO_Livox, maybe you can open a new issue in their repo
