### ISSUE TITLE
Request for Dockerfile to Accommodate Custom Dependencies

### ISSUE THREAD

**Issue by lytkinsa96** [PJLab-ADG/Livox-Mapping#37]
Hello my friend!

I am currently working on developing lidar odometry algorithms and came across your project which I find extremely insightful and relevant to my work.

I noticed that the repository currently offers a link to download a Docker image. While this is incredibly helpful, I am not using ROS and need to modify the environment to include specific dependencies critical to my project.

Could you please provide the Dockerfile used to create the Docker image? Having access to the Dockerfile would allow me to make the necessary modifications and fully utilize your algorithms with my setup.

Thank you for considering my request. I appreciate the work you've put into this project and am looking forward to potentially contributing to it as well.

Best regards,
Lytkin Sergey.

**Comment by SiyuanHuang95** [comment]
Hi,

Thanks for your interest in our project.

Actually, the DockerHub have already parsed the docker image in the docker file line by line, as found in [DockerHub](https://hub.docker.com/layers/siyuanhuang95/livox_slam/release/images/sha256-ca4c4c09c25f31585e4fb2cbd6340a673913f675fe8c8d804120d63473b2f852?context=explore). You can just pick the lines that necessary for you.

Bests,
