### ISSUE TITLE
maybe something wrong

### ISSUE THREAD

**Issue by chengwei0427** [PJLab-ADG/Livox-Mapping#8]
Hi, @SiyuanHuang95 

I change the param **SLIDEWINDOWSIZE** from 2 to 3 in Estimator.h, and test the bag **casual_walk.bag** which lio_sam privode.

After lidar-imu inited, the trajectory drift .Used topics: /points_raw and /imu_raw. 
The extrinsics lidar -> IMU: 
 extrinsicTrans: [0.0, 0.0, 0.0]
  extrinsicRot: [-1, 0, 0,
                  0, 1, 0,
                  0, 0, -1]

![2022-03-24 11-31-40屏幕截图](https://user-images.githubusercontent.com/20199999/159837899-b7baa9b9-ba2d-48f2-96e3-8cdbc8c0606e.png)

If set the SLIDEWINDOWSIZE=2, the program is normal.

![2022-03-24 11-34-17屏幕截图](https://user-images.githubusercontent.com/20199999/159837984-c04150cc-1dac-4f03-9ca1-37048aceca07.png)

The bag contains two imu topics(/imu_raw and /imu_correct). 

If used /imu_corrcect as the imu input, The extrinsics lidar -> IMU: 
 extrinsicTrans: [0.0, 0.0, 0.0]
  extrinsicRot: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

Whether the **SLIDEWINDOWSIZE** is 2 or 3, the program is normal.

It's strange, and maybe something wrong with the extrinsics params in the code.

Do you have a similar problem? Or any Suggestions?

**Comment by SiyuanHuang95** [comment]
Have not met that issue. No further suggestions could be given. When you find anything interesting, you are quite welcome to share with us.

**Comment by lhthq** [comment]
hi~ I see you issue.    In the terminal, there  are  “cannot create a KD-Tree with an empty input cloud”？ Why?

**Comment by chengwei0427** [comment]
> hi~ I see you issue. In the terminal, there are “cannot create a KD-Tree with an empty input cloud”？ Why?

There are three KD-trees, corresponding to the three types of features(edge, surf and non), you could check the three types of feature, maybe one of them is empty.

**Comment by chengwei0427** [comment]
[https://github.com/TixiaoShan/LIO-SAM/issues/204](url)

**Comment by SiyuanHuang95** [comment]
> [https://github.com/TixiaoShan/LIO-SAM/issues/204](url)

Cannot catch your main idea, was the transformation matrix will cost this issue?

Real url:

[https://github.com/TixiaoShan/LIO-SAM/issues/204](https://github.com/PJLab-ADG/Livox-Mapping/issues/url)

**Comment by SiyuanHuang95** [comment]
Since there is no further update, I will close this issue.
